os: linux
dist: focal
language: ruby
rvm:
  - 2.7

before_install:
  - yes | gem update --system --force --no-document
  - gem install bundler --no-document

script: script/cibuild.sh

branches:
  only:
    - main
